### PR TITLE
Additional sort parameters.

### PR DESCRIPTION
**Pull request by elcct**

### CODE REVIEW

**Comment by elcct** [comment]
@jim68000 do we need to have generated clients included in the project?

**Comment by reupen** [comment]
Too much noise to see what's changed :cry:

**Comment by jim68000** [comment]
Yeah, I usually commit just the revised swagger component files as part of a PR, and then generate the server etc after that PR is merged and just push that to master

**Comment by elcct** [comment]
Closing this mess :)

**Pull request closed without merging**
